---

- name: dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items:
    - python3-setuptools
    - python3-bcrypt
    - python3-passlib
    - python3-vobject
    - python3-dateutil
    - git-core

- name: set radicale executable
  set_fact:
    radicale_executable: "/usr/local/bin/radicale"

- name: radicale is downloaded
  git:
    repo: "{{ radicale_git_url }}"
    version: "{{ radicale_version }}"
    dest: "{{ radicale_download_dir }}"
    update: true
    depth: 1
  notify: restart radicale

- name: radicale is installed
  command: python3 setup.py install
  args:
    chdir: "{{ radicale_download_dir }}/"
    creates: "{{ radicale_executable }}"
