---

- name: dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  loop:
    - python3-pip
    - python3-setuptools
    - python3-bcrypt
    - python3-passlib

- name: set radicale executable
  set_fact:
    radicale_executable: "/usr/local/bin/radicale"

- name: radicale is installed
  pip:
    name: radicale
    version: "{{ radicale_version }}"
    executable: pip3
  notify: restart radicale
